### ISSUE TITLE
API return no results

### ISSUE THREAD

**Issue by ZeyuL01** [inutano/chip-atlas#100]
Dear Team,

Hope you are all doing well, I tried to use API to automatically conduct enrichment analysis for my gene lists. However after I posted my data, I didn't get any result.

Commands I used:

curl -X POST \
-d "format=text" \
-d "result=www" \
-d "genome=hg38" \
-d "antigenClass=TFs and others" \
-d "cellClass=All cell types" \
-d "threshold=50" \
-d "typeA=gene" \
--data-urlencode "bedAFile@test1.txt" \
-d "typeB=refseq" \
-d "bedBFile=empty" \
-d "permTime=1" \
-d "title=test_api" \
-d "descriptionA=test_set" \
-d "descriptionB=control" \
-d "distanceUp=50" \
-d "distanceDown=50" \
https://ddbj.nig.ac.jp/wabi/chipatlas/

Response I got:
requestId: wabi_chipatlas_2023-0206-0324-26-709-800611
parameters: null
current-time: 2023-02-06 03:28:54
start-time: 
current-state: 

Status page:
request-ID: wabi_chipatlas_2023-0206-0324-26-709-800611
status: not-found
current-time: 2023-02-06 03:47:36
system-info: 

I tried to check the status by using the returned requestId, the status page always shows "not-found", so I'm not sure which part I did wrong. Any advice for how to fix this would be very appreciate. 

Many thanks,

Zeyu

**Comment by shinyaoki** [comment]
Hi Zeyu,

We apologize for any inconvenience caused. Recently we had to temporarily suspend the API service due to a user submitting too many jobs. It is now back to normal and we would appreciate it if you could try again.

Best,
Shinya

**Comment by ZeyuL01** [comment]
Hi Dr. Oki,

I just tried and it is working fine now, really thank you for the help. Besides, may I ask if there is a capacity limitation for ChIP.Atlas? Because I also have quite a lot gene lists to run, if that's a problem I may add a pause between two tasks.

Thanks,
Zeyu

**Comment by shinyaoki** [comment]
Due to this incident, we have set a limit of up to 100 jobs. We can temporarily waive this limit on request. How many gene lists do you have?

**Comment by ZeyuL01** [comment]
I have ~1700 gene lists, each with 200-1000 genes. If that's possible I'd be very thankful, otherwise I can add a 30mins pause between every 50 jobs, since I'm also running my scripts on HPC cluster, 2-3 days should be enough to finish all of them.

**Comment by shinyaoki** [comment]
I would be grateful if you could submit 50 jobs at 30 minute intervals.

**Comment by ZeyuL01** [comment]
Sure, really thank you for the help!
