### ISSUE TITLE
Web application -- Trying to use "Analyze" >> "Colocalization" gives error

### ISSUE THREAD

**Issue by c2b2pss** [inutano/chip-atlas#105]
Hi,

At this page (image below):
https://i.ibb.co/1Xqd5tv/Screenshot-2023-04-30-11-26-53.jpg

trying to use "Analyze">>"Colocalization" gives following error

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>hg38/target/SRX11222445.1.html</Key>
<BucketName>data</BucketName>
<Resource>/data/hg38/target/SRX11222445.1.html</Resource>
<RequestId>175ABF7579C7699A</RequestId>
<HostId>d38dcae4-ca01-4d5d-b838-0988933a694a</HostId>
</Error>
```
Your help is appreicated!!

**Comment by shinyaoki** [comment]
Hi,

The Colocalisation tool is used to search for TFs that colocalise with a given TF. As SRX11222445 is ATAC-seq data but not TF ChIP-seq data, there is no data for the Colocalisation tool. Instead you can use the Enrichment Analysis tool where you can submit the peak regions of SRX11222445 and you will find the TFs that show enriched binding to the submitted peak regions.

Best,

Shinya
