### ISSUE TITLE
Enrichment analysis not functioning - no posted downtime

### ISSUE THREAD

**Issue by slsevilla** [inutano/chip-atlas#116]
I was attempting to use the Enrichment analysis feature but was prompted with this error:

```
Enrichment analysis is currently unavailable due to the background server issue. See maintainance schedule on top page.
```

There is no downtime or maintenance schedule posted at the top of the page, so it did not appear to be scheduled.

**Comment by inutano** [comment]
Hi @slsevilla thank you for raising the issue! There was an issue on the background server we use for the function which caused the error you got. Now the server is back and the function is working fine. Sorry for the inconvenience, and thank you for using the app!
