### ISSUE TITLE
Diff analysis download error

### ISSUE THREAD

**Issue by ftmir** [inutano/chip-atlas#117]
Hi, I'm trying to download the diff analysis data but am getting this error. Could you please help with this:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
query/wabi_chipatlas_2024-0116-0838-56-582-309605.zip
</Key>
<BucketName>data</BucketName>
<Resource>
/data/query/wabi_chipatlas_2024-0116-0838-56-582-309605.zip
</Resource>
<RequestId>17AAAA0EB866249E</RequestId>
<HostId>d38dcae4-ca01-4d5d-b838-0988933a694a</HostId>
</Error>

**Comment by zouzhaonan** [comment]
Hi, ftmir.

This issue occurred due to a failure in transferring the Diff Analysis results to the public server, which has already been resolved.
Please download the results again from https://chip-atlas.dbcls.jp/data/query/wabi_chipatlas_2024-0116-0838-56-582-309605.zip.

BR,
Zhaonan

**Comment by ftmir** [comment]
Thanks for helping with this. But this seems to happen every time we try to download files from the website.
Could you please also help with this one:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
query/wabi_chipatlas_2024-0116-2049-53-261-054790.zip
</Key>
<BucketName>data</BucketName>
<Resource>
/data/query/wabi_chipatlas_2024-0116-2049-53-261-054790.zip
</Resource>
<RequestId>17AAD143D9005B0C</RequestId>
<HostId>d38dcae4-ca01-4d5d-b838-0988933a694a</HostId>
</Error>

**Comment by zouzhaonan** [comment]
Hi, ftmir

This issue seems to occur due to an intermittent malfunction in the background supercomputer. We have tried to reduce the likelihood of this happening. Please try again and kindly let us know if the problem persists.

BR,
Zhaonan

**Comment by ftmir** [comment]
Hi I'm still having problems with the Diff analysis. when I put multiple SRX IDs for two groups I get:  
![ERROR] : The organism should be .
!! Abnormal termination !! Please check the parameters or contact the administers.

Is this because I'm mixing data from different studies?
Please find the result I got instead of a bed file in the attachment.
Thanks again for your help. 

[wabi_chipatlas_2024-0122-0459-03-900-752093.zip](https://github.com/inutano/chip-atlas/files/14002781/wabi_chipatlas_2024-0122-0459-03-900-752093.zip)

**Comment by shinyaoki** [comment]
I think the number of SRXs you entered is too high (n > 100). Try with a smaller number of SRXs (n < 10) because this tool is designed to analyze multiple SRXs.

**Comment by zouzhaonan** [comment]
It appears that you were including a space after SRX1568633, such as "SRX1568633 ", which caused the Diff Analysis to fail due to the space. We have now fixed this issue. Thank you for your important report.

In addition, as Shinya pointed out, you entered an excessive number of SRXs. This can lead to a significant consumption of CPU time and resources, which is not advisable. Although it depends on your goal, we generally recommend comparing SRXs from the same experiment series to eliminate artificial batch effects.
