### ISSUE TITLE
experimentList.tab not include all samples?

### ISSUE THREAD

**Issue by ZeyuL01** [inutano/chip-atlas#118]
Hi,

I'm trying to download the "TFs and others" bed files for hg38 genome, however I noticed the number of available samples does not equal to the number showing in the web portal. In web portal there should be 30300 samples in the category of "TFs and others" for hg38, however in the experimentList.tab I only found around 10000 samples, is there a reason for this?

Thanks,

Zeyu

**Comment by shinyaoki** [comment]
Hi Zeyu,

Try the following command.
`curl https://chip-atlas.dbcls.jp/data/metadata/experimentList.tab| awk -F'\t' '$2 == "hg38" && $3 == "TFs and others"'| wc -l`
You will see that there are 30,300 data for "TFs and others" for hg38.

Best,
Shinya

**Comment by ZeyuL01** [comment]
Hi Shinya,

I tried the command as you suggested, It successfully returned the count of 30,300 entries. This was very helpful, thank you!

Best regards,

Zeyu
