### ISSUE TITLE
Do you have zipped version of bed files?

### ISSUE THREAD

**Issue by zx8754** [inutano/chip-atlas#121]
I am trying to get this bed file - https://chip-atlas.dbcls.jp/data/hg19/assembled/Oth.Prs.05.AllAg.AllCell.bed - the size is ~14GB. The download time eta is around 2 hours, and it failed to download couple of times.

Is there a zipped version of this file?

**Comment by shinyaoki** [comment]
Hi,

I have prepared a gzip file from the bed file of your request. You can download it from the following URL:
https://chip-atlas.dbcls.jp/data/share/Oth.Prs.05.AllAg.AllCell.bed.gz
Could you let me know after the download?

Shinya

**Comment by zx8754** [comment]
@shinyaoki  Great, this is ~8 times smaller, it took only about 3 minutes to download. Thank you, very helpful.

For future, will other files can be shared as zipped files, too?

One more question, do you have checksums (`md5sum` ?) for these files?

**Comment by shinyaoki** [comment]
Thanks for letting me know about your download. I'm sorry, but I have no plans to share zipped files or checksums.
