### ISSUE TITLE
hg38 bw download ERROR 404: Not Found.

### ISSUE THREAD

**Issue by ZhengYi999** [inutano/chip-atlas#134]
I am attempting to download some bigwig files for transcription factors in the hg38 genome assembly. When I try to use wget with the command 'wget https://chip-atlas.dbcls.jp/data/hg38/eachData/bw/ERX1149088.bw', I encounter a 404 Not Found error. 
![未命名1718855484](https://github.com/inutano/chip-atlas/assets/173329679/81cc53f5-af20-46c1-a212-a225800461d4)

Similarly, when I attempt to open the download link in a web browser, I receive an error message.
![image](https://github.com/inutano/chip-atlas/assets/173329679/219d36ab-249b-4764-badc-0307c67f8839)
 
Am I using the incorrect method to download the data?

**Comment by zouzhaonan** [comment]
Hi @ZhengYi999 ,

We're so sorry for the inconvenience. This issue is due to a temporary server error, and we're working hard to solve it. We'll have it fixed in no time, probably in a few days.

Before then, I can send you a zip file with the BED and bigWig files you need. Please kindly let me know which accession IDs (ERXs) you need.

BR,
Zhaonan

**Comment by ZhengYi999** [comment]
Hi Zhaonan,

I would greatly appreciate your assistance! Here is my experimental ID
[K562_TF_Experimental_ID.txt](https://github.com/user-attachments/files/15910094/K562_TF_Experimental_ID.txt)

**Comment by ZhengYi999** [comment]
Hi Zhaonan,

I would greatly appreciate your assistance! Here is my experimental ID
[K562_TF_Experimental_ID.txt](https://github.com/user-attachments/files/15910102/K562_TF_Experimental_ID.txt)

Best regards,

Zhengyi

**Comment by zouzhaonan** [comment]
Hi Zhengyi,

We have re-uploaded the files of your request as priority. You can now download them from the following links:
https://chip-atlas.dbcls.jp/data/hg38/eachData/bw/_SRX_.bw
https://chip-atlas.dbcls.jp/data/hg38/eachData/bed05/_SRX_.05.bed
* Replace '\_SRX\_' with actual experimental IDs in the TXT file.

BR,
Zhaonan

**Comment by ZhengYi999** [comment]
Hi Zhaonan,

I can download files from the links，thank you so much ！！

Best regards,
Zhengyi
