### ISSUE TITLE
Bisulfite Enrichment Analysis - Forever Running

### ISSUE THREAD

**Issue by slizarazo21** [inutano/chip-atlas#139]
Hi!

I am trying to do overlaps over all the Bisulfite dataset, when I subset for a specific cell type, the analysis goes without any problem, but if I choose all the cells with 100 permutations, the analysis never ends.

I have tried using fewer genes (let's say only two), and the analysis still appears running but never stops. Please see the picture

I am using H.sapiens (hg38)

<img width="620" alt="Screenshot 2024-09-21 at 6 58 13 PM" src="https://github.com/user-attachments/assets/1e867aa2-0da7-4b79-8cbf-0af6e69ecb49">

**Comment by zouzhaonan** [comment]
Hi,

Thank you for bringing this to our attention. It seems there might be a bug in the backend analysis pipeline. We have made some adjustments and believe the issue may be resolved now. Could you kindly try running the analysis again and let us know if the problem persists?

We would appreciate any feedback you can provide.

BR,
Zhaonan

**Comment by slizarazo21** [comment]
Hi!

Thank you so much for such a quick response!
I did the analysis again and everything is fine right now!

Thanks again!
