### ISSUE TITLE
Cannot find Separate Bed files

### ISSUE THREAD

**Issue by MariaCartolano** [inutano/chip-atlas#140]
Hello

thank you for this great resource! 

After inspecting the data I noticed that I am better off downloading separate bed files, selected based on the sample origin.
In fact, after having downloaded the assembled peaks, I noticed that the sample source is quite heterogeneous ( e.g. samples from healthy and diseased patients are assembled together) and it does not help me. 

I have been selecting the original bed files of interest upon manual filtering of the experimentList file and I was going to download them from

http://dbarchive.biosciencedbc.jp/kyushu-u/hg19/eachData/bed05/

however in this directory I cannot find the bed files I am looking for. 
Can you please help me?

This is the list of files I am interested in:

SRX8083175 | hg19 | ATAC-Seq | Blood | Naive B cells
SRX8083176 | hg19 | ATAC-Seq | Blood | Naive B cells
SRX8083177 | hg19 | ATAC-Seq | Blood | Naive B cells
ERX9147763 | hg19 | ATAC-Seq | Blood | Memory B cells
ERX9147764 | hg19 | ATAC-Seq | Blood | Memory B cells
ERX9147766 | hg19 | ATAC-Seq | Blood | Memory B cells
ERX9147767 | hg19 | ATAC-Seq | Blood | Memory B cells
ERX9147769 | hg19 | ATAC-Seq | Blood | Memory B cells
ERX9147770 | hg19 | ATAC-Seq | Blood | Memory B cells
SRX11161005 | hg19 | H3K27me3 | Blood | Naive B cells
SRX16495765 | hg19 | H3K27me3 | Blood | Naive B cells
SRX16495766 | hg19 | H3K27me3 | Blood | Naive B cells
SRX16500133 | hg19 | H3K27me3 | Blood | Naive B cells
SRX16500134 | hg19 | H3K27me3 | Blood | Naive B cells
SRX11159883 | hg19 | H3K9me3 | Blood | Memory B cells
SRX11159884 | hg19 | H3K9me3 | Blood | Memory B cells
SRX11167811 | hg19 | H3K9me3 | Blood | Memory B cells
SRX11167812 | hg19 | H3K9me3 | Blood | Memory B cells

Thank you for your help
Maria

**Comment by shinyaoki** [comment]
Hi Maria,

Thank you for using ChIP-Atlas. The URL you tested is old. The current URL is as follows:
https://chip-atlas.dbcls.jp/data/hg19/eachData/bed05/SRX8083175.05.bed

See also the documentation page to learn more about the URLs.
https://github.com/inutano/chip-atlas/wiki#9-downloads

Best,
Shinya

-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  
OKI, Shinya, PhD, Professor
IRDA (Institute of Resource Development and Analysis),
Kumamoto University
606 GTC Bldg, 2-2-1 Honjo, Chuo-ku,
Kumamoto 860-0811, Japan
tel: +81-96-373-6501
https://oki-lab.jp/en/

**Comment by MariaCartolano** [comment]
ohi!
Thank you so much for the swift reply! I did not notice there were 2 different links. I found the old one in a closed issue .
Sorry about that !

maria
