### ISSUE TITLE
Enrichment analysis hanging

### ISSUE THREAD

**Issue by sgourisankar** [inutano/chip-atlas#141]
Hi,
First of all let me congratulate you and your team on a terrific resource, it is really user-friendly too. Now for the issue - I have been trying to run a couple of enrichment analyses of bed files and they have been hanging for > 12 hours. The analyses were estimated to take 16-17 mins each. Is there an issue with the server? The Request ID for one of them is 
wabi_chipatlas_2024-1028-1225-33-760-433954.

Thank you so much.

**Comment by shinyaoki** [comment]
Hi,

Thank you for using ChIP-Atlas. As posted in the news section of the Home Page, we have confirmed that there is a problem with some of the ChIP-Atlas server functions. So far, the analysis itself runs normally, but users cannot view the results even after it is finished. If you need the results of the analysis, please send a direct mail to me (okishinya [at] kumamoto-u.ac.jp). I will reply to you with the results of the analysis as an attachment. We apologize for any inconvenience and thank you for your patience during the server recovery process.

Best,
Shinya

**Comment by sgourisankar** [comment]
Dear Shinya,
No problem. Thank you for the help.

Could I please obtain these results of these 12 analyses:

wabi_chipatlas_2024-1028-1228-36-998-902408
wabi_chipatlas_2024-1028-1229-04-358-453308
wabi_chipatlas_2024-1028-1229-31-73-739471
wabi_chipatlas_2024-1028-1229-56-415-244310
wabi_chipatlas_2024-1028-1230-22-18-959261
wabi_chipatlas_2024-1028-1230-46-12-838695

wabi_chipatlas_2024-1028-1224-59-227-135680
wabi_chipatlas_2024-1028-1225-33-760-433954
wabi_chipatlas_2024-1028-1226-03-551-178697
wabi_chipatlas_2024-1028-1226-55-323-167250
wabi_chipatlas_2024-1028-1227-24-57-987599
wabi_chipatlas_2024-1028-1227-49-188-426871

Thank you,
Sai

On Oct 28, 2024, at 5:43 PM, Shinya Oki ***@***.***> wrote:



Hi,

Thank you for using ChIP-Atlas. As posted in the news section of the Home Page, we have confirmed that there is a problem with some of the ChIP-Atlas server functions. So far, the analysis itself runs normally, but users cannot view the results even after it is finished. If you need the results of the analysis, please send a direct mail to me (okishinya [at] kumamoto-u.ac.jp). I will reply to you with the results of the analysis as an attachment. We apologize for any inconvenience and thank you for your patience during the server recovery process.

Best,
Shinya

**Comment by inutano** [comment]
closing this, but let us know if you still need our help @sgourisankar
