### ISSUE TITLE
Download err

### ISSUE THREAD

**Issue by tan5251** [inutano/chip-atlas#142]
Hi. The Bw files of Bisulfite-Seq can not be dowoload, Can you check it? Thanks

**Comment by zouzhaonan** [comment]
Could you specify which experiments (SRX IDs) you are trying to download the BigWig files for?

**Comment by tan5251** [comment]
Thanks for you reply.  Here is my IDs:
SRX1649893
SRX1649893
SRX1651654
SRX1651655
SRX1651657
SRX1651658
SRX1651659
SRX381713
SRX8564069

**Comment by tan5251** [comment]
It seem that all BS-seq can not to be download. All I have download is blank files. ATAC-seq and Chip-seq is normal to be download.

**Comment by zouzhaonan** [comment]
In my environment, I can successfully download the files using the method shown in the attached PDF. Could you please confirm if you have tried this approach?
[bs_bw_dl.pdf](https://github.com/user-attachments/files/17798722/bs_bw_dl.pdf)
