### ISSUE TITLE
Suggested average score cut-off for target genes

### ISSUE THREAD

**Issue by kimaguresilvia** [inutano/chip-atlas#15]
Hi there! Thank you for developing a very powerful instrument to study gene regulation. 
I am interested in the prediction of target genes of a group of Transcription Factors. 

Which average score should I consider as cut-off to identify a gene as target of one TF? 1000?

Thank you for your help

**Comment by shinyaoki** [comment]
HI,

Thank you for using ChIP-Atlas.
There is no cut-off value agreed by everyone, but, the scores more than 100 look to be reliable by browsing BigWig data on IGV, based on my experience.

Best,
Shinya
