### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by mdippel-benaroya** [inutano/chip-atlas#152]
Hi! I am try to download some peaks from the ChIP-Atlas peak browser and I unable to click Download BED file. I was able to download a bed file yesterday, but somehow I am unable to do so now. Is there anything that I need to do to get the bed file that I am not seeing? Thank you!

![Screenshot](https://github.com/user-attachments/assets/cc5c352b-93fe-4579-92c4-87feb610d542)

**Comment by zouzhaonan** [comment]
The ChIP-Atlas backend server is currently undergoing annually maintenance. Please refer to the maintenance notice displayed on the top page (https://chip-atlas.org/).

**Comment by inutano** [comment]
@mdippel-benaroya Now it's back. Thank you for your patience!
