### ISSUE TITLE
Cannot Download Peak-Call Data 

### ISSUE THREAD

**Issue by dwu937** [inutano/chip-atlas#16]
Hello! Thank you for this great tool.

Last month I have downloaded some ChIP-seq peak call data from your website, and have been using it since. I need to download the data again, but for some reason I get an error when I try to download some of the data. For example, if I try to download this bed file http://dbarchive.biosciencedbc.jp/kyushu-u/hg19/eachData/bed10/SRX670629.10.bed I get a 404 error. I also tried going to https://chip-atlas.org/view?id=SRX670629 and downloading the data there, but I also get a 404 error. Last month I was able to get this data with no problems. Do you know why this is the case? Thank you!

Best,
David Wu

**Comment by shinyaoki** [comment]
Hi David,

I am sorry for the late response.
For unknown reason, some experiments have been deleted from the public data server. I'll recover such deleted data by next update of ChIP-Atlas.

Best,
Shinya
