### ISSUE TITLE
How peak calling done 

### ISSUE THREAD

**Issue by Hemantcnaik** [inutano/chip-atlas#29]
Hello nice tool, I just want ask how this peak calling done using macs2 with or without input because i was seeing  Methods not able follow up can you please provide me script or explain how you used the tool

**Comment by shinyaoki** [comment]
Hi,

Thank you for using ChIP-Atlas. The method of peak-calling is described in the paper of ChIP-Atlas.
https://www.embopress.org/doi/full/10.15252/embr.201846255 <https://www.embopress.org/doi/full/10.15252/embr.201846255>

Cheers,

Shinya

**Comment by Hemantcnaik** [comment]
I read it but only mentioned about parameter used peak calling. does it used Input or not mentioned, Can u please provide me command used for peak calling. It will be very helpfull

**Comment by shinyaoki** [comment]
We don’t use input file for peak-calling. Following command is used for peak-calling for human data with Q value cut-off:
macs2 callpeak -t <filename>.bam -f BAM -g hs -n <filename> -q 1e-5

**Comment by Hemantcnaik** [comment]
Okay Thank you, is there any reason not using the input file as a control because most of chip-seq analysis use input as control

**Comment by shinyaoki** [comment]
The main reason is that it is much difficult to find an input data corresponding to given ChIP-seq data. We thus prepared peak-call data of input data, which will be useful to know genomic regions biased to be peak-called.

**Comment by Hemantcnaik** [comment]
Thank you. it was helpful
