### ISSUE TITLE
peaknumber difference compared to paper and chip-atlas 

### ISSUE THREAD

**Issue by luckysardar** [inutano/chip-atlas#30]
Hello Thank you for the chip-atlas 

I was trying to see the data from the  "SRX1334361" ID when I was went through the literature and chip-atlas peak number both are vary lot for the this data

From chipatlas 
mm9
Number of total reads
56287990
Reads aligned (%)
92.2
Duplicates removed (%)
24.4
Number of peaks
559 (qval < 1E-05)

when I see the paper and GEO(ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1907nnn/GSM1907178/suppl/GSM1907178_45693_peaks.bed.txt.gz)

peak number 1303 as per the paper (https://www.sciencedirect.com/science/article/pii/S1934590916000667#app3)
peak number are different any comment on this 

Thank u

--

**Comment by inutano** [comment]
Hello @luckysardar thank you for using ChIP-Atlas! As we employ our [unified data processing pipeline](https://github.com/inutano/chip-atlas/wiki#primary_processing_doc) for all the archived data, the available results including the number of peaks may vary from the original data processing as you indicated. We cannot tell the reason for each case, but probably the results in the publication used input control to remove the noises, while ChIP-Atlas does not. Hope this helps!

**Comment by luckysardar** [comment]
I did not get without input is very less peak and with input increase in the peak number how is this posible

**Comment by shinyaoki** [comment]
The number of peaks will be affected by not only the use of input but also the difference of the tools and algorithms for alignment and peak-calling.
