### ISSUE TITLE
Error - Something went wrong: Please let us know to fix the problem,

### ISSUE THREAD

**Issue by PFRoux** [inutano/chip-atlas#31]
Hi !

Thanks a lot for this amazing resource.

I am getting the following message when trying to run an analysis :

`Something went wrong: Please let us know to fix the problem, click 'contact us' below this page.{"readyState":4,"responseText":"<h1>Internal Server Error</h1>","status":500,"statusText":"error"}`

Best,

Pef

**Comment by shinyaoki** [comment]
Hi Pef,

Could you tell me the details on what did you do with ChIP-Atlas related to the error?

Shinya
