### ISSUE TITLE
ChIP-atlas enrichment analysis queued for ever

### ISSUE THREAD

**Issue by alexyfyf** [inutano/chip-atlas#34]
Hi team, 
The chip-atlas is of great help to us and I really like this project.
However, I've experience problems running enrichment analysis which takes several days and still showing queued.
I cannot find any log or error message so I'm not sure what is the problem.
Can your team have a look at this?
I've tried both narrowPeak and BED format, and neither worked.

Cheers,
Alex

**Comment by inutano** [comment]
Hello Alex, can you send me your job id embedded in the URL of the job status page to inutano@gmail.com? We may be able to look at the log of our backend server. Thanks for using!

**Comment by alexyfyf** [comment]
Thank you for your help.
I've sent through the job ids.

**Comment by inutano** [comment]
Last week our backend server received too many jobs and temporarily took a long time to run the Enrichment Analysis jobs. Now the issue is solved and we'll try to avoid this kind of problem happen in the future.
