### ISSUE TITLE
Improvement Suggestions on Dataset Search

### ISSUE THREAD

**Issue by mortunco** [inutano/chip-atlas#37]
Hello, 

I cant thank you enough for providing such a wonderful resource for everybody. Not only the processing part, data in your website is sometimes easier to search than GEO datasets.

I have couple suggestions for more accurate dataset search.

1) Could you add a search button to dataset search sections? Something results come up as I type also I live in canada so sometimes i dont know if the server is searching on the background or just frozen.
2) Could you maybe add a literal search option. My favorite proteins are AR and ER. But these almost exist in any word. 
3) Also search only in specific field such as Antigens maybe.

I unfortunately don't know how these can be implemented so forgive my ignorance if its already thought.

Best regards,

Tunc.

**Comment by shinyaoki** [comment]
Hi Tunc,

Thank you for using ChIP-Atlas.
I also think that the Dataset Search service will be better if having column search function. I’ll update the service in near future and, instead, I ask you to download TSV data by which you can perform column search with Excel.

Best,

Shinya

**Comment by mortunco** [comment]
thank you very much !
