### ISSUE TITLE
MACS2 score

### ISSUE THREAD

**Issue by rojinsafavi** [inutano/chip-atlas#38]
How can I get the MACS2 scores? 
Not sure if this is correct, but I basically downloaded the BigWig, and converted that to bedGraph. The columns are as follow, is the last column the MACS2 score?

```
#bedGraph section chr1:10000-36225
chr1    10000   10001   0.0524468
chr1    10001   10002   0.0786702
chr1    10002   10003   0.104894
chr1    10003   10004   0.118005
chr1    10004   10005   0.15734
chr1    10005   10006   0.196676
```

**Comment by shinyaoki** [comment]
Hi,

This is an example of the URL for peak-call data.
http://dbarchive.biosciencedbc.jp/kyushu-u/hg19/eachData/bed05/SRX018625.05.bed
 <http://dbarchive.biosciencedbc.jp/kyushu-u/hg19/eachData/bed05/SRX018625.05.bed>The MACS2 sores are shown on the fourth column.

Best,

Shinya

**Comment by Zengggg** [comment]
Hi,

It seems that the columns of peak-call data are changed. Can you explain the name of each column? Thank you.
Example:  
[https://chip-atlas.dbcls.jp/data/hg19/eachData/bed05/SRX4394193.05.bed]

**Comment by shinyaoki** [comment]
Hi,

The peak call data in ChIP-Atlas follows the output format of macs2 peak-caller and has not been changed.
https://github.com/macs3-project/MACS/blob/master/docs/callpeak.md#output-files

Best,
Shinya

**Comment by Zengggg** [comment]
Thank you.
