### ISSUE TITLE
Missing data for SRX2409974

### ISSUE THREAD

**Issue by karl616** [inutano/chip-atlas#4]
Hi,
I wanted to use data from your service, but stumbled over a problem when trying to download data for SRX2409974. Trying to understand why, it looks like the alignment failed. At least the alignment rate is 0%. Is this really correct? Or is it simply a processing error? I also do not understand how you can filter out 14% duplicates with 0% aligned reads? This results in 0 peaks. This is an Encode sample and their processing, admittedly different, comes out with ~64k peaks:
https://www.encodeproject.org/files/ENCFF169XNB/

If it is a processing error, it might be the case it happened for several samples... Could that be?

Another example is SRX083227 with 0.9% aligned reads, 28% duplicates and 3 peaks.

What do you think?

**Comment by shinyaoki** [comment]
Hi Karl,

I found that the most of the reads of SRX2409974 and SRX083227 have technical sequences as shown in atatched QC results, although such technical sequences are usually removed prior to submitting to SRA or GEO.

Exact alignment rate of SRX2409974 was 6.9E-06 (= 214 / 31167642), and 14 % (= 30 / 214) of aligned read was PCR duplicate.

Cheers,
Shinya

**Comment by karl616** [comment]
Hi Shinya,
thank you for the clarification.  I understand the numbers and the problem now. 

The last half of each read is adapter. As an end-user, of course I would like to see these things handled, but I also see the complications. It would probably require reprocessing of a lot of data.

I'll close this issue...
