### ISSUE TITLE
portal to database

### ISSUE THREAD

**Issue by CoryFunk** [inutano/chip-atlas#5]
I'm wondering if there's a way for us to access your database for a project we're working on. We're hoping your database exists in something like a sql database as we're running a shiny app, displaying ChIP-seq data in IGV. We would love to work with you on this. tagging @paul-shannon (with whom I'm working).

**Comment by felipealbrecht** [comment]
Hello,

The DeepBlue Epigenomic Data Server imports the data from chip atlas and
makes it accessible through its api. It can be also accessed through its
R/Bioconductor package - DeepBlueR.

**Comment by paul-shannon** [comment]
@felipealbrecht  - thank you, great tip!  I will be looking into DeepBlueR later today.

**Comment by inutano** [comment]
Hi @felipealbrecht, thank you for the heads-up! Can we describe the information on our documentation of the ChIP-Atlas? Any preferable documentation page for that?

**Comment by paul-shannon** [comment]
@felipealbrecht  Just taking my first look at DeepBlueR, read the man pages and the vignette, ran through some of the examples.  Good stuff here - but I am a little confused about formulating my typical queries.

For example, in naive pseudo-code, to obtain all the ChIP-seq hits in a small region of the hg38 genome:
````
tbl.hits <- query(deepblue, project="ChIP-atlas", genome="hg38",
                  region="chr2:233,054,878-233,112,822")
````
Could you point me in the right direction?

**Comment by inutano** [comment]
Hi @paul-shannon, probably you should create an issue on @felipealbrecht 's repo so that he can manage it! https://github.com/felipealbrecht/DeepBlue-Manual
