### ISSUE TITLE
mis assignment of 100s of samples

### ISSUE THREAD

**Issue by fgualdr** [inutano/chip-atlas#54]
Hi,

it came acros to my attention that several samples are mis annotated.
One example is: SRX4663216 which is a chips for H3K27ac while in the ATLAS is annotated as H3K27me3 chips.
Is there a reason why this happens,

Thanks.

**Comment by shinyaoki** [comment]
Hi,

Thank you for your report. This is clearly of our mistake in the curation, and we’ll improve it by the next update of ChIP-Atlas. Please feel free to tell us any other mis annotation.

Thanks,

Shinya
