### ISSUE TITLE
ever queued in Enrichment Analysis

### ISSUE THREAD

**Issue by Masaya-YAMAZAKI** [inutano/chip-atlas#55]
Hi

I'm running Enrichment Analysis, but the status is 'queued' ever.
Can your team have a look at this?

Regards,
Masaya

**Comment by shinyaoki** [comment]
Hi Masaya,

Thank you for using ChIP-Atlas.
The comupting server for ChIP-Atlas enrichment analysis (NIG Super Computer) is now so crowded that you may have to wait for a long time until other queries are processed.
Please take a note of URLs of you queries.

Best, 
Shinya
