### ISSUE TITLE
Peak viewer not working

### ISSUE THREAD

**Issue by user-sol** [inutano/chip-atlas#6]
****Hi, I like very much the idea of this project and wanted to explore the tool. I went to peak browser and selected TF, then left all cell types and then chose PARP1 in antigen, when I click over "View on IGV" the page doesn't work. It takes me to this link:
http://localhost:60151/load?genome=hg19&file=http://dbarchive.biosciencedbc.jp/kyushu-u/hg19/assembled/Oth.ALL.05.PARP1.AllCell.bed

Best, 
Sol

**Comment by inutano** [comment]
Hi @user-sol, you need to install and launch [IGV](http://software.broadinstitute.org/software/igv/) before click the button. See the instruction movies for [installing IGV](https://www.youtube.com/watch?v=JVWLlzIedw8&feature=youtu.be) and [peak browser](https://www.youtube.com/watch?v=qKNOkK-8hDo&feature=youtu.be). Thanks!
