### ISSUE TITLE
ChIP-Atlas: Dataset Search : No data available in table

### ISSUE THREAD

**Issue by samanthaconte** [inutano/chip-atlas#69]
I'm trying to search for datasets or cell types through the "ChIP-Atlas Dataset Search" web page. Whatever the query, the response remains "No data available in table". Is there something wrong with the server or is there something I missed ? 

Thanks a lot for helping

Below is a screenshot with a query SRX1583885 which is normally available in the database.

![image](https://user-images.githubusercontent.com/80245515/173825002-aee858b1-2f9f-4bfc-b80c-887d97010ffb.png)

**Comment by inutano** [comment]
Hi @samanthaconte , thanks for raising an issue. The advanced search function fetches a large file from our remote server for building a search index, so it takes a time or may not work if your network is unstable. 

When you open the advanced search page, it will show the table like this first (may take a few seconds or longer):
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/221804/173966495-d3fe7bfc-f9fa-4df2-8cce-da749f0868a3.png">

And on my laptop it works as expected with your query:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/221804/173966276-17dcf73f-342c-4b6a-be99-ca57add298e8.png">

Please check your network condition, and if it still does not work, could you check if your browser console raised an error?

Feel free to reopen this issue if the problem persists!
