### ISSUE TITLE
restrict ChIP-Atlas Peak Browser to a genomic region?

### ISSUE THREAD

**Issue by paul-shannon** [inutano/chip-atlas#7]
@inutano  I am delighted to discover ChIP-Atlas.  Here at the Institute for Systems Biology I work on Bioconductor packages (trena, trenaViz, MotifDb, ...)  all of which are complementary to the data you provide, and will become stronger as a result.

I wonder if the the helpful user interface you provide  https://chip-atlas.org/peak_browser could be extended so that one can specify a genomic region (for instance hg38 or hg19 chr2:127,015,600-127,181,721) to constrain the query?     This would allow us to obtain a small bed file quickly.

Forgive me if this constraint is already provided and I overlooked it.

**Comment by inutano** [comment]
Hello @paul-shannon, thank you for using ChIP-Atlas! It's our pleasure that we could help your products.

The peak browser itself does not have a function to serve a part of a bed file, unfortunately. But, to reduce the network traffic, we're using bed file index (.bed.idx) which is originally introduced as an extension of the bed file format by the IGV team. The index files exist in the same directory of the target bed files like `ftp.biosciencedbc.jp:/archive/chip-atlas/data/hg19/assembled/Unc.Utr.50.Unclassified.AllCell.bed` and `ftp.biosciencedbc.jp:/archive/chip-atlas/data/hg19/assembled/Unc.Utr.50.Unclassified.AllCell.bed.idx`. 

Therefore I think you can use the index files to retrieve a part of bed file, but we don't know the specification nor the program to read the index files. If you think this would be a help, please ask the IGV team how to use it.

Hope this helps!

**Comment by paul-shannon** [comment]
Thanks @inutano.    Index files are, as you suggest, very helpful for subsetting large genomic files.  They are often used with byte-range capable webservers for just this purpose.  So far as I know, they always reside in the same directory as the large file they serve to index.
  
The missing piece, if I am not mistaken, is how to use the indexes you describe with the ChIP-ATLAS peak browser.   Maybe we can make this a feature request?   

If I am not presuming too much, it could work like this: 

- The peak browser UI allows us to input a genomic range
-  When the peak browser server gets the request (with Antigen Class, Cell Type & Threshold) it also gets the genomic range
-  The peak browser server uses the index file to extract only the region of interest

Possible someday?

Thank you!

-
