### ISSUE TITLE
backend server not working lately

### ISSUE THREAD

**Issue by FanBioinformatics** [inutano/chip-atlas#70]
Hi there,

I have been having problems redoing this enrichment analysis. First run with cellClass defined as Neural, no problem. recently, I reran the same analysis, no results yielded for all my peak set with the same setting. then I wanted to try with all cell types included, the script is shown as below, no results returned. would you help out here?

curl -X POST \
  -d "format=text" \
  -d "result=www" \
  -d "genome=hg38" \
  -d "antigenClass=TFs and others" \
  **### -d "cellClass=All cell types" \**
  -d "threshold=05" \
  -d "typeA=bed" \
  --data-urlencode "bedAFile@bed_Y_38_trajectory_regions.bed" \
  -d "typeB=bed" \
  --data-urlencode "bedBFile@bed_background_peaks.bed" \
  -d "permTime=1" \
  -d "title=bed_Y_38_trajectory_regions.bed_TFs and others"\
  -d "descriptionA=my data" \
  -d "descriptionB=random permutation 10 times" \
  -d "distanceUp=0" \
  -d "distanceDown=0" \
  https://ddbj.nig.ac.jp/wabi/chipatlas/ >> file_bed_Y_38_trajectory_regions.bed_TFs_and_others.txt

best, 
huihui

**Comment by shinyaoki** [comment]
Hi huihui,

I tested the enrichment analysis with the GUI tool, and finished it successfully. So, could you test your analysis with GUI tool?
http://chip-atlas.org/enrichment_analysis

Best,
Shinya

**Comment by IAMHUIHUI** [comment]
Yeah, GUI works. But I have more than a dozen peak files to test, backend is not just convenient, but also helps prevent input errors.

Thanks,
Huihui

From: Shinya Oki ***@***.***>
Date: Wednesday, June 22, 2022 at 1:40 AM
To: inutano/chip-atlas ***@***.***>
Cc: IAMHUIHUI ***@***.***>, Author ***@***.***>
Subject: Re: [inutano/chip-atlas] backend server not working lately (Issue #70)

Hi huihui,

I tested the enrichment analysis with the GUI tool, and finished it successfully. So, could you test your analysis with GUI tool?
http://chip-atlas.org/enrichment_analysis

Best,
Shinya

**Comment by shinyaoki** [comment]
Could you show me the error message when you execute the curl command?

**Comment by IAMHUIHUI** [comment]
This is written when I submit the request:
I don’t receive error message, but when I download the result, nothing is in  the file.

requestId: wabi_chipatlas_2022-0621-0105-03-153-059689
parameters: null
current-time: 2022-06-21 01:05:03
start-time:
current-state:
requestId: wabi_chipatlas_2022-0621-0111-55-72-713787
parameters: null
current-time: 2022-06-21 01:11:55
start-time:
current-state:

From: Shinya Oki ***@***.***>
Date: Wednesday, June 22, 2022 at 8:28 AM
To: inutano/chip-atlas ***@***.***>
Cc: IAMHUIHUI ***@***.***>, Author ***@***.***>
Subject: Re: [inutano/chip-atlas] backend server not working lately (Issue #70)

Could you show me the error message when you execute the curl command?

**Comment by shinyaoki** [comment]
Due to a recent internal programming change, we have found that the API could not correctly conveys the values of "-d threshold=". This was our mistake and we apologize for the inconvenience. From now on, please make sure that the value of "-d threshold=" is entered as 50, 100, 200, or 500, which is 10x values of the past ones (05, 10, 20, or 50).

We revised the API manual for the changed threshold values.
https://github.com/inutano/chip-atlas/wiki/Perform-Enrichment-Analysis-programmatically

**Comment by IAMHUIHUI** [comment]
I see. Thanks for the clarification. I will test it out and let you know
how it goes.

Best,
Huihui

**Comment by shinyaoki** [comment]
Hi huihui,

I tested the enrichment analysis with the GUI tool, and finished it successfully. So, could you test your analysis with GUI tool?
http://chip-atlas.org/enrichment_analysis <http://chip-atlas.org/enrichment_analysis>

Best,
Shinya
