### ISSUE TITLE
bug in alignment %

### ISSUE THREAD

**Issue by alexyfyf** [inutano/chip-atlas#75]
I'm skimming the logs for data, I noticed an >100% alignment rate for this data.
https://chip-atlas.org/view?id=SRX373733
Also I have checked the `experimentList.tab` file, and found the same percentage. Not sure if this is a bug or something else.

Alex

**Comment by shinyaoki** [comment]
Hi Alex,

This is the bug occured when the experiment is paired-end sequence. We will fix the bug by the next update of ChIP-Atlas.

Shinya

**Comment by alexyfyf** [comment]
Noted, thanks! So it is not related to the peak bed files? Just related to the calculation of percentage?

**Comment by shinyaoki** [comment]
This is just related to the calculation of percentage. We apologize for the inconvenience.
