### ISSUE TITLE
GSE145157 for CHIP-ATLAS

### ISSUE THREAD

**Issue by MonicaLiao1227** [inutano/chip-atlas#89]
Dear Team,

Thank you for developing the ChIP-Atlas. 
It provides a user-friendly system for fast visualizing of the results.

Recently, I'm looking for the hypoxia TF in the Peak Browser. 
Unfortunately, the GSE145157 dataset is not included in the ChIP-Atlas; I wonder if it is possible to have the dataset in ChIP-Atlas.

Sequencing data have been deposited to the National Center for Biotechnology Information GEO database.

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE145157

Thanks,

Monica

**Comment by shinyaoki** [comment]
Hi Monica,

We apologize for the inconvenience. The data for GSE145157 has already been analyzed and uploaded to ChIP-Atlas server, but it is not viewable from the web page by our mistakes. We will fix it by the next update, but it may take long time as we are planning a major modification. If you are in a hurry, please let me know the ID (GSMxxxx) so I can give you the URL for the BigWig and Bed files.

Best,

Shinya

**Comment by MonicaLiao1227** [comment]
GSM4307706 | HCT116, normoxia, replicate 1, HIF1A ChIP
-- | --
GSM4307707 | HCT116, normoxia, replicate 2, HIF1A ChIP
GSM4307708 | HCT116, hypoxia, replicate 1, HIF1A ChIP
GSM4307709 | HCT116, hypoxia, replicate 2, HIF1A ChIP
GSM4307710 | RKO, normoxia, replicate 1, HIF1A ChIP
GSM4307711 | RKO, normoxia, replicate 2, HIF1A ChIP
GSM4307712 | RKO, hypoxia, replicate 1, HIF1A ChIP
GSM4307713 | RKO, hypoxia, replicate 2, HIF1A ChIP


</body>
</html>[GSM4307706](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307706)	HCT116, normoxia, replicate 1, HIF1A ChIP
[GSM4307707](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307707)	HCT116, normoxia, replicate 2, HIF1A ChIP
[GSM4307708](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307708)	HCT116, hypoxia, replicate 1, HIF1A ChIP
[GSM4307709](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307709)	HCT116, hypoxia, replicate 2, HIF1A ChIP
[GSM4307710](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307710)	RKO, normoxia, replicate 1, HIF1A ChIP
[GSM4307711](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307711)	RKO, normoxia, replicate 2, HIF1A ChIP
[GSM4307712](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307712)	RKO, hypoxia, replicate 1, HIF1A ChIP
[GSM4307713](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4307713)	RKO, hypoxia, replicate 2, HIF1A ChIP

**Comment by shinyaoki** [comment]
Your requested data are available from foloowing URLs:

# ID
```
SRX ID      GEO ID      Sample                                     
SRX7712484  GSM4307706  HCT116, normoxia, replicate 1, HIF1A ChIP  
SRX7712485  GSM4307707  HCT116, normoxia, replicate 2, HIF1A ChIP  
SRX7712486  GSM4307708  HCT116, hypoxia, replicate 1, HIF1A ChIP   
SRX7712487  GSM4307709  HCT116, hypoxia, replicate 2, HIF1A ChIP   
SRX7712488  GSM4307710  RKO, normoxia, replicate 1, HIF1A ChIP     
SRX7712489  GSM4307711  RKO, normoxia, replicate 2, HIF1A ChIP     
SRX7712490  GSM4307712  RKO, hypoxia, replicate 1, HIF1A ChIP      
SRX7712491  GSM4307713  RKO, hypoxia, replicate 2, HIF1A ChIP      
```
# BigWig
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712484.bw
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712485.bw
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712486.bw
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712487.bw
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712488.bw
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712489.bw
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712490.bw
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bw/SRX7712491.bw

# Peak-call (Q < 1E-05)
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712484.05.bed
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712485.05.bed
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712486.05.bed
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712487.05.bed
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712488.05.bed
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712489.05.bed
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712490.05.bed
http://dbarchive.biosciencedbc.jp/kyushu-u/hg38/eachData/bed05/SRX7712491.05.bed
