### ISSUE TITLE
control file for TF ChIP

### ISSUE THREAD

**Issue by gaotc200** [inutano/chip-atlas#90]
Hi,

With MAC2, I assume you use something like this for peak calling:
```
macs2 callpeak -t experiment.bam -c input.bam (other parameters...)
```
and I'm looking for a way to have that `experiment.bam` vs `input.bam` relation for the TF ChIP-seq experiments, so that I could further analysis the data. Unfortunately I don't see any such one-to-one relationship in experimentList.tab or fileList.tab, or other places on the website. Could you help with this? Thank you very much.

Best,
Jiahao

**Comment by shinyaoki** [comment]
Hi Jiahao,

We do not use `input.bam` for peak-calling because it is difficult to find an `input.bam` corresponding with an `experiment.bam`.

Best,
Shinya

**Comment by gaotc200** [comment]
Good to know. Thank you for your response.
