### ISSUE TITLE
Cannot access Chip-See data despite downloading IVG and  required settings 

### ISSUE THREAD

**Issue by hetvish** [inutano/chip-atlas#95]
<img width="1277" alt="Screen Shot 2023-01-17 at 1 46 27 PM" src="https://user-images.githubusercontent.com/122923455/212985178-8f676597-e021-4bd8-af58-2d031b71d35e.png">
<img width="1260" alt="Screen Shot 2023-01-17 at 1 46 33 PM" src="https://user-images.githubusercontent.com/122923455/212985181-fc4fd71a-b198-4723-ac11-8342ad7b1aab.png">

Hello, 
I am struggling to access the Chip-Sea data for mouse for TF binding regions and I cannot access the information. The data is not going to IVG despite downloading it and setting the correct port. 

Can you please help me as it is crucial for my project.

**Comment by shinyaoki** [comment]
Hi,

Did you launch IGV before clicking on "View on IGV" button of Peak Browser Web page?
I was able to view the data with the settings you sent me (TFs data of mm10 adipocytes).

Shinya

**Comment by hetvish** [comment]
I did launch the IGv before clicking on the view on IGV. it worked for me today but there are times it does not. Maybe it is just a glitch
