### ISSUE TITLE
% Reads mapped > 100

### ISSUE THREAD

**Issue by gdolsten** [inutano/chip-atlas#96]
Hi, in this entry: DRX011916 the processing logs are as follows:

52549766,158.0,19.3,1716

How is it possible that 158.0% of the reads were mapped?  Does this have some other meaning?

**Comment by shinyaoki** [comment]
This is clearly our mistake. We'll improve it by the next update.

**Comment by gdolsten** [comment]
It could be that for paired end results you treat them differently

**Comment by shinyaoki** [comment]
Understood. Thank you for pointing that out.
