### ISSUE TITLE
How to combine data track

### ISSUE THREAD

**Issue by Very1989** [inutano/chip-atlas#99]
Dear Team,
Thank you for developing the ChIP-Atlas.

I'm unable to perform a combined analysis and obtained a list of target genes. 
In particular, I'm looking for all the putative target genes of very unexplored TFs hetero-dimers in the human blood cell lines.

From ChIP-Atlas: Peak Browser I selected all the experimental conditions for the two TF of interest (human genome, ChIP from TFs, blood cell, threshold of 100, and the antigen protein of interest), visualizing the binding with IGV genome browser. Of course, if I select a particular gene I can see if there is a peak in the same position for both proteins. My problem is that I would like to obtain a list of the total genes of the genome with overlapped peaks for both proteins (possibly near the TSS). I tried with the "combined data track" tool in the IGV software, but it doesn't allow me to select the tracks. 

How can I perform this type of analysis? I tried also with ChIP-Atlas: Target Genes, selecting the distance of +/-1kb from TSS for both proteins, but I'm unable to obtain a list of genes.

Thank you for your support.

Best regards,
Veronica De Paolis

**Comment by shinyaoki** [comment]
Hi Veronica,

The BED file describing the coordinates of TSSs of all genes is available from following URL:
https://chip-atlas.dbcls.jp/data/others/lib/TSS/TSS.GENOME.bed
* Replace "GENOME" with an appropreate genome assembly name such as "hg38" and "mm10".

These files have been made from refFlat.txt provided from UCSC genome browser.
https://hgdownload.soe.ucsc.edu/goldenPath/GENOME/database/refFlat.txt.gz

Best,
Shinya
